### ISSUE TITLE
Retrieve User Data

### ISSUE THREAD

**Issue by andrelcunha** [andrelcunha/got_it#2]
Fetch user name and email from the configuration file using the `config` command.

### **Dependencies:** 
- Completion of `config` command.

### Tasks:
-  [ ] Create tests for fetching `user.name` and `user.email`
 - [x]  Fetch `user.name`
 - [x] Fetch `user.email`
 - [x] Log user information for commit metadata.
